events {}

http {

    upstream waf {
        server python_waf:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://waf;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
